{
    pkgs,
    base16SchemeNoHashtag,
}:
with base16SchemeNoHashtag;
    pkgs.writeText "swaylock_config" ''
        # Generated by Sonnet 4.6 because
        # I have spent enough time tweaking colours
        color=${base00}
        inside-color=${base01}
        inside-clear-color=${base02}
        inside-caps-lock-color=${base02}
        inside-ver-color=${base0D}
        inside-wrong-color=${base08}
        ring-color=${base03}
        ring-clear-color=${base0A}
        ring-caps-lock-color=${base09}
        ring-ver-color=${base0D}
        ring-wrong-color=${base08}
        line-color=${base00}
        line-clear-color=${base00}
        line-caps-lock-color=${base00}
        line-ver-color=${base00}
        line-wrong-color=${base00}
        text-color=${base05}
        text-clear-color=${base0A}
        text-caps-lock-color=${base09}
        text-ver-color=${base06}
        text-wrong-color=${base08}
        key-hl-color=${base0C}
        bs-hl-color=${base0F}
        separator-color=00000000
        font=monospace
        font-size=16
        indicator-radius=75
        indicator-thickness=10
    ''
